
import React from "react";
const DummyProduct = [
  {
    _id: "1",
    name: "Basmati Rice 5kg",
    price: 450,
    offerPrice: 420,
    image: ["https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg"],
    category: "Organic",
    description: ["c"],
    inStock: true,
  },
  {
    _id: "2",
    name: "Wheat Flour 5kg",
    price: 320,
    offerPrice: 300,
    image: ["https://images.pexels.com/photos/4110256/pexels-photo-4110256.jpeg"],
    category: "Organic",
    description: ["Fresh wheat flour", "Rich in fiber", "Ideal for chapati"],
    inStock: true,
  },
  {
    _id: "3",
    name: "Sugar 1kg",
    price: 45,
    offerPrice: 40,
    image: ["https://images.pexels.com/photos/4110262/pexels-photo-4110262.jpeg"],
    category: "Organic",
    description: ["Refined white sugar", "Fine texture", "Sweet and pure"],
    inStock: true,
  },
  {
    _id: "4",
    name: "Sunflower Oil 1L",
    price: 140,
    offerPrice: 130,
    image: ["https://images.pexels.com/photos/5946971/pexels-photo-5946971.jpeg"],
    category: "Organic",
    description: ["Healthy cooking oil", "Light and pure", "Cholesterol free"],
    inStock: true,
  },
  {
    _id: "5",
    name: "Milk 1L",
    price: 55,
    offerPrice: 50,
    image: ["https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg"],
    category: "Dairy",
    description: ["Fresh full cream milk", "Rich in calcium", "Daily essential"],
    inStock: true,
  },
  {
    _id: "6",
    name: "Bread Loaf",
    price: 30,
    offerPrice: 28,
    image: ["https://images.pexels.com/photos/2434/bread-food-healthy-breakfast.jpg"],
    category: "Bakery",
    description: ["Soft fresh bread", "Perfect for breakfast", "Baked daily"],
    inStock: true,
  },
  {
    _id: "7",
    name: "Eggs (12 pcs)",
    price: 75,
    offerPrice: 70,
    image: ["https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg"],
    category: "Dairy",
    description: ["Farm fresh eggs", "High protein", "12 pieces pack"],
    inStock: true,
  },
  {
    _id: "8",
    name: "Apples 1kg",
    price: 120,
    offerPrice: 110,
    image: ["https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg"],
    category: "Fruits",
    description: ["Fresh red apples", "Juicy and sweet", "1kg pack"],
    inStock: true,
  },
  {
    _id: "9",
    name: "Bananas (6 pcs)",
    price: 40,
    offerPrice: 35,
    image: ["https://images.pexels.com/photos/461208/pexels-photo-461208.jpeg"],
    category: "Fruits",
    description: ["Fresh ripe bananas", "6 pieces", "Healthy snack"],
    inStock: true,
  },
  {
    _id: "10",
    name: "Onions 1kg",
    price: 28,
    offerPrice: 25,
    image: ["https://images.pexels.com/photos/533342/pexels-photo-533342.jpeg"],
    category: "Vegetables",
    description: ["Fresh onions", "Strong flavor", "1kg pack"],
    inStock: true,
  },
  {
    _id: "11",
    name: "Tomatoes 1kg",
    price: 35,
    offerPrice: 30,
    image: ["https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg"],
    category: "Vegetables",
    description: ["Fresh tomatoes", "Rich in vitamins", "Perfect for cooking"],
    inStock: true,
  },
  {
    _id: "12",
    name: "Carrots 1kg",
    price: 40,
    offerPrice: 35,
    image: ["https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg"],
    category: "Vegetables",
    description: ["Crunchy carrots", "Rich in beta-carotene", "Healthy choice"],
    inStock: true,
  },
  {
    _id: "13",
    name: "Cabbage",
    price: 30,
    offerPrice: 25,
    image: ["https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg"],
    category: "Vegetables",
    description: ["Fresh cabbage", "Green and crispy", "Ideal for salads"],
    inStock: true,
  },
  {
    _id: "14",
    name: "Cauliflower",
    price: 45,
    offerPrice: 40,
    image: ["https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg"],
    category: "Vegetables",
    description: ["Farm fresh cauliflower", "White and fresh", "Daily cooking essential"],
    inStock: true,
  },
  {
    _id: "15",
    name: "Green Chillies 250g",
    price: 20,
    offerPrice: 18,
    image: ["https://images.pexels.com/photos/5945878/pexels-photo-5945878.jpeg"],
    category: "Vegetables",
    description: ["Fresh green chillies", "Spicy flavor", "250g pack"],
    inStock: true,
  },
  {
    _id: "16",
    name: "Coriander Leaves",
    price: 15,
    offerPrice: 12,
    image: ["https://images.pexels.com/photos/4198168/pexels-photo-4198168.jpeg"],
    category: "Vegetables",
    description: ["Fresh coriander leaves", "Aromatic", "Perfect garnish"],
    inStock: true,
  },
  {
    _id: "17",
    name: "Orange Juice 1L",
    price: 110,
    offerPrice: 100,
    image: ["https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg"],
    category: "Beverages",
    description: ["Fresh orange juice", "Rich in vitamin C", "1L bottle"],
    inStock: true,
  },
  {
    _id: "18",
    name: "Mineral Water 1L",
    price: 20,
    offerPrice: 18,
    image: ["https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg"],
    category: "Beverages",
    description: ["Pure mineral water", "1L bottle", "Safe and refreshing"],
    inStock: true,
  },
  {
    _id: "19",
    name: "Cornflakes 500g",
    price: 150,
    offerPrice: 140,
    image: ["https://images.pexels.com/photos/4198019/pexels-photo-4198019.jpeg"],
    category: "Snacks",
    description: ["Crispy cornflakes", "Healthy breakfast", "500g pack"],
    inStock: true,
  },
  {
    _id: "20",
    name: "Chocolate Bar",
    price: 50,
    offerPrice: 45,
    image: ["https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg"],
    category: "Snacks",
    description: ["Delicious chocolate", "Sweet treat", "Premium quality"],
    inStock: true,
  },
  {
    _id: "21",
    name: "Ice Cream 500ml",
    price: 120,
    offerPrice: 110,
    image: ["https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg"],
    category: "Frozen",
    description: ["Creamy ice cream", "500ml pack", "Perfect dessert"],
    inStock: true,
  },
  {
    _id: "22",
    name: "Paneer 200g",
    price: 90,
    offerPrice: 85,
    image: ["https://images.pexels.com/photos/5946663/pexels-photo-5946663.jpeg"],
    category: "Dairy",
    description: ["Fresh paneer", "High protein", "200g pack"],
    inStock: true,
  },
  {
    _id: "23",
    name: "Yogurt Cup",
    price: 25,
    offerPrice: 20,
    image: ["https://images.pexels.com/photos/373882/pexels-photo-373882.jpeg"],
    category: "Dairy",
    description: ["Fresh yogurt", "Creamy texture", "Single serving cup"],
    inStock: true,
  }
];

export default DummyProduct;
  